# Set colorscheme
colorscheme palenight

# Load standard kak autoload
nop %sh{
    ln -ns "$kak_runtime/autoload" "$kak_config/autoload/kak_std_load"
}

# Highlighters
add-highlighter global/ number-lines
add-highlighter global/ show-matching

# Options
set-option global tabstop 4
set-option global indentwidth 4
set-option global ui_options terminal_assistant=none

# Declare custom modes
declare-user-mode buff

# User mode keymap
map -docstring "Comments current line" global user c ":comment-line<ret>"
map -docstring "Enters Buffer mode" global user b ":enter-user-mode buff<ret>"

# Buffer mode keymap
map -docstring "Closes the current buffer" global buff c ":db<ret>"
map -docstring "Goes to the next buffer" global buff n ":bn<ret>"
map -docstring "Goes to the previous buffer" global buff p ":bp<ret>"
# TODO:
# 	- Find a way to list all buffers
# 	- Find a way to close all buffers but the current one

# Plugin configs
set-option global auto_pairs ( ) { } [ ] '"' '"' "'" "'" ` `
enable-auto-pairs
