[[language]]
name = "zig"
scope = "source.zig"
file-types = ["zig"]
roots = []
comment-token = "//"
auto-format = true
formatter = { command = "git", args = ["stripspace"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
scope = "source.cpp"
file-types = ["cpp", "hpp"]
roots = []
comment-token = "//"
auto-format = true
formatter = { command = "git", args = ["stripspace"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
scope = "source.c"
file-types = ["c", "h"]
roots = []
comment-token = "//"
auto-format = true
formatter = { command = "git", args = ["stripspace"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "nasm"
scope = "source.asm"
file-types = ["asm", "s", "S"]
roots = []
comment-token = ";"
auto-format = true
formatter = { command = "git", args = ["stripspace"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "make"
comment-token = "#"
auto-format = true
formatter = { command = "git", args = ["stripspace"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "meson"
comment-token = "#"
auto-format = true
formatter = { command = "git", args = ["stripspace"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "nix"
scope = "source.nix"
file-types = ["nix"]
roots = []
comment-token = "#"
auto-format = true
formatter = { command = "git", args = ["stripspace"] }
indent = { tab-width = 2, unit = "  " }
